#!/opt/flocker/bin/python

# -*- coding: utf-8 -*-
import re
import sys
import os

from flocker.node.script import AgentService, AgentServiceFactory, flocker_container_agent_main

"""
Grab the agent IP from the environment and monkey-patch the agent script
to use that IP rather than auto-detect
"""
FLOCKER_DATASET_IP = os.environ.get('FLOCKER_DATASET_IP')

def get_external_ip_from_env(self, host, port):
    return unicode(FLOCKER_DATASET_IP, "ascii")

if FLOCKER_DATASET_IP is not None:
    AgentService.get_external_ip = get_external_ip_from_env
    AgentServiceFactory.get_external_ip = get_external_ip_from_env

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(flocker_container_agent_main())